Algoritmo "Questão 14"
// Disciplina  : FLA
// Professor   : Raphael Muniz
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Heitor Queiroga Duarte
// Data atual  : 19/08/2020
Var
   n, d: real
Inicio
   escreva("Digite o primeiro número: ")
   leia(n)
   escreva("Digite o segundo número: ")
   leia(d)
   escreval("A soma deles é ", n + d)
   escreval("O produto deles é", n * d)
   escreval("O quociente deles é ", n / d)
Fimalgoritmo