Algoritmo "Questão 11"
// Disciplina  : FLA
// Professor   : Raphael Muniz
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Heitor Queiroga Duarte
// Data atual  : 19/08/2020
Var
   n, d: inteiro
Inicio
   escreva("Digite um número: ")
   leia(n)
   escreva("Digite o seu divisor: ")
   leia(d)
   escreval("O quociente de divisão é ", n / d)
   escreva("O resto de sua divisão é ", n % d)
Fimalgoritmo