frase = str('Heitor é lindo')
print('Funções de formatação de textos:')
ct = input('Pressione "enter" para continuar:')
print('-----1-----')
print(frase.count('o'))
print('-----2-----')
print(frase.find('tor'))
print(frase.find('xfklgju'))
print('-----3-----')
print(len(frase))
print('-----4-----')
print('Heit' in frase)
print('-----5-----')
print(frase.replace('lindo', 'bonito'))
print('-----6-----')
print(frase)
print('-----7-----')
print(frase.upper())
print('-----8-----')
print(frase.lower())
print('-----9-----')
